### ISSUE TITLE
Installing Flowistry failed when the specific Rust toolchain isn't installed

### ISSUE THREAD

**Issue by dacut** [willcrichton/flowistry#13]
# Problem
Installing Flowistry failed. Looks like Flowistry wants a specific version of the toolchain, but that fails to install via Flowistry.

Installing it separately works as expected.

# Logs

**OS:** darwin (20.6.0)
**VSCode:** 1.60.2
**Error message**
```
error: component download failed for cargo-x86_64-apple-darwin: could not rename downloaded file from '/Users/dacut/.rustup/downloads/a8674a2e1c94fe147f0fb05303de67130dc6dfc9b33f2eb9a07194a5b85ee2ec.partial' to '/Users/dacut/.rustup/downloads/a8674a2e1c94fe147f0fb05303de67130dc6dfc9b33f2eb9a07194a5b85ee2ec'
```
```
**Full log:** https://paste.rs/8md
Activating...
Workspace root	/Users/dacut/projects/WCP
Running command: 	cargo +nightly-2021-09-23 flowistry -V
error: toolchain 'nightly-2021-09-23-x86_64-apple-darwin' is not installed

Running command: 	rustup toolchain install nightly-2021-09-23 -c rust-src,rustc-dev,llvm-tools-preview
info: syncing channel updates for 'nightly-2021-09-23-x86_64-apple-darwin'
info: latest update on 2021-09-23, rust version 1.57.0-nightly (308dffd25 2021-09-22)
info: downloading component 'cargo'
error: component download failed for cargo-x86_64-apple-darwin: could not rename downloaded file from '/Users/dacut/.rustup/downloads/a8674a2e1c94fe147f0fb05303de67130dc6dfc9b33f2eb9a07194a5b85ee2ec.partial' to '/Users/dacut/.rustup/downloads/a8674a2e1c94fe147f0fb05303de67130dc6dfc9b33f2eb9a07194a5b85ee2ec'
flowistry is activated
```

**Comment by willcrichton** [comment]
Thanks for the report @dacut! Do you have an idea why `rustup` would fail when run through VSCode but not through your shell? It seems like a permissions issue.

Either way, I could add a recommendation for users to run `rustup` themselves if it fails in VSCode.

**Comment by dacut** [comment]
Ah, I think I figured out what might have happened.

I suspect a VSCode extension, likely rust-analyzer, decided to muck with the install in parallel; in essence, I had two copies of rustup running (without me knowing) and the `.partial` file got moved out from under the Flowistry instance of rustup.

I'm not sure what to do here; hopefully this is temporary (until the stable version of rust has the features needed for Flowistry to run).

**Comment by willcrichton** [comment]
Sadly, Flowistry will always have to use nightly, because it uses Rust's internal compiler API which will never be stable.

I'll look into whether rust-analyzer is the culprit.

**Comment by willcrichton** [comment]
After some discussion in the #wg-rustup discord, it seems like this isn't an easily solvable issue: https://discord.com/channels/442252698964721669/463480252723888159/892919117940686939

So in 2f0f843d46995367bf20f76b43315a7199bca70d I added a workflow for allowing the user to manually run rustup and then telling Flowistry when to continue installing. I think this is the only option until https://github.com/rust-lang/rustup/issues/988 gets solved, so I'm closing this for now.

Please reopen this issue if the workaround does not solve your problem.

**Comment by dacut** [comment]
Sounds good! Thanks for digging into this! Definitely not an issue at all for me; I was just reporting it in case others hit it (and since the tool asked me so nicely to do so :-) ).
