### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by rpavlik** [willcrichton/flowistry#15]
# Problem
Just tried to install the extension with a workspace open to some rust code. Debian buster, I think I had nightly set as default for the current project? I normally default to stable.

# Logs

**OS:** linux (5.10.0-0.bpo.8-amd64)
**VSCode:** 1.60.1
**Error message**
```
error: failed to install component: 'cargo-x86_64-unknown-linux-gnu', detected conflict: 'etc/bash_completion.d/cargo'
```

**Full log:** https://paste.rs/o22

**Comment by willcrichton** [comment]
Thanks for the bug report @rpavlik. It seems like there's a problem with your system configuration and rustup. Can you try running this command and let me know what happens?

```
rustup toolchain install nightly-2021-09-23 -c rust-src,rustc-dev,llvm-tools-preview
```

**Comment by rpavlik** [comment]
```
info: syncing channel updates for 'nightly-2021-09-23-x86_64-unknown-linux-gnu'
info: latest update on 2021-09-23, rust version 1.57.0-nightly (308dffd25 2021-09-22)
info: component 'llvm-tools-preview' for target 'x86_64-unknown-linux-gnu' is up to date
info: component 'rust-src' is up to date
info: component 'rustc-dev' for target 'x86_64-unknown-linux-gnu' is up to date

  nightly-2021-09-23-x86_64-unknown-linux-gnu unchanged - rustc 1.57.0-nightly (308dffd25 2021-09-22)

info: checking for self-updates
```

**Comment by willcrichton** [comment]
Ok, well that seems to work. Try this one last command. If this works you should be good to go.

```
cargo +nightly-2021-09-23 install flowistry --force
```

**Comment by willcrichton** [comment]
Going to close this for now unless the issue arises again.
