### ISSUE TITLE
Trouble using

### ISSUE THREAD

**Issue by rpavlik** [willcrichton/flowistry#16]
# Problem
This is probably part of #15 but didn't see how to get the logs out without filing a new issue. This happens when I choose "backwards highlight" as suggested by the notification. (That said, I unset the config for this directory so it should fallback to this default:

```
stable-x86_64-unknown-linux-gnu (default)
rustc 1.55.0 (c8dfcfe04 2021-09-06)
```
)

 FWIW, I also use Fish shell so might all be related to #9 

# Logs

**OS:** linux (5.10.0-0.bpo.8-amd64)
**VSCode:** 1.60.1
**Error message**
```
error: the 'cargo' binary, normally provided by the 'cargo' component, is not applicable to the 'nightly-2021-09-23-x86_64-unknown-linux-gnu' toolchain
```

**Full log:** https://paste.rs/wXq

**Comment by willcrichton** [comment]
Closing this for now, further discussion should be in #15.
