### ISSUE TITLE
Flowistry doesn't work on proc-macro crates

### ISSUE THREAD

**Issue by luke-biel** [willcrichton/flowistry#21]
As in title, I'm getting an error:
```
Flowistry could not run because your project failed to build with error:
error: Found argument '--proc-macro' which wasn't expected, or isn't valid in this context

USAGE:
    cargo rustc --package <SPEC> --profile <PROFILE-NAME> --quiet

For more information try --help
```

To reproduce:
* Generate new project using cargo generate with https://github.com/intellij-rust/rust-procmacro-quickstart-template
* Try to search backwards on any variable

**Comment by willcrichton** [comment]
Thanks for the bug report @luke-biel! I'll take a look this week.
