### ISSUE TITLE
Prebuilt Flowistry binaries have incorrect rustc library paths on ARM targets

### ISSUE THREAD

**Issue by ArbilGit** [willcrichton/flowistry#25]
Hi,

The extension seems to install fine (there's the Flowistry context menu), but choosing any action opens the pane with:

    Flowistry could not run because your project failed to build with error:
    error: failed to run `rustc` to learn about target-specific information

    Caused by:
    process didn't exit successfully: `/Users/me/.cargo/bin/flowistry-driver rustc - --crate-name ___ --print=file-names --crate-type bin --crate-type rlib --crate-type dylib --crate-type cdylib --crate-type staticlib --crate-type proc-macro --print=sysroot --print=cfg` (signal: 6, SIGABRT: process abort signal)
    --- stderr
    dyld: Library not loaded: @rpath/librustc_driver-ac2715475dad8249.dylib
        Referenced from: /Users/me/.cargo/bin/flowistry-driver
        Reason: image not found

OS: macOS 11.6 (Darwin arm64 20.6.0)
VSCode: 1.62.0-insider

I searched through closed isues and couldn't find one like this. Thanks in advance!

**Comment by willcrichton** [comment]
Hi @ArbilGit, sorry I didn't respond to your question sooner.

Just to confirm, if you run with the latest Flowistry, do you still get the same issue?

**Comment by ArbilGit** [comment]
Hi, yup, the same. I do get the "Flowistry has successfully installed!" popup on installing again, the error stays the same. I removed everything flowistry related from .cargo/bin beforehand, is there anything else I need to do for clean reinstall?

**Comment by willcrichton** [comment]
Can you let me know what the output of this script is:

```
export TARGET_LIBDIR=$($(rustup which --toolchain nightly-2021-10-08 rustc) --print target-libdir)
echo $TARGET_LIBDIR
ls $TARGET_LIBDIR
```

**Comment by ArbilGit** [comment]
Apparently a different version of the librustc_driver:

libaddr2line-8e90a501e7d06bdb.rlib
libadler-3c4362acc80457f8.rlib
libaho_corasick-89d63ecccfdb08e8.rlib
liballoc-326e86e4bea117d8.rlib
libannotate_snippets-de0c4254821f4fa8.rlib
libansi_term-3918f97efba09ebc.rlib
libarrayvec-170a39e9dc6bf735.rlib
libatty-113afb882e277c3f.rlib
libbitflags-52bfff178e4baf28.rlib
libblock_buffer-51deaf3ba2acf860.rlib
libcc-b2a4d46235e9c7d1.rlib
libcfg_if-0ee92ca16dbeded9.rlib
libcfg_if-839d994187df8152.rlib
libcfg_if-cfff621afdaadb9d.rlib
libchalk_derive-a2436ad52deb4a3e.dylib
libchalk_engine-19298834193ddea2.rlib
libchalk_ir-19996f9ed4cdb0c7.rlib
libchalk_solve-7aab60ff51104a33.rlib
libchrono-35838d58965b0b70.rlib
libcompiler_builtins-6a11cd41524cd818.rlib
libcore-dd6de681850a671c.rlib
libcrc32fast-07109554902ffeff.rlib
libcrossbeam_deque-9b6fa711a19353fb.rlib
libcrossbeam_epoch-f7928a803cc02752.rlib
libcrossbeam_queue-2291cca13562bd9b.rlib
libcrossbeam_utils-79eae481b7dcbed0.rlib
libcstr-da6c62751885a93f.dylib
libdatafrog-551cadeaa871166a.rlib
libdigest-e854e032613656d5.rlib
libeither-0b54fa10487c5d04.rlib
libena-971e887c2c9e92ca.rlib
libfixedbitset-576751970c457489.rlib
libgeneric_array-768daa8daa06a33d.rlib
libgetopts-33662cc73df72555.rlib
libgetopts-b117d2af67d33f38.rlib
libgetrandom-c814550af9f9a668.rlib
libgetrandom-c9abeccecbe5a42e.rlib
libgimli-ab471a0d725e5cd8.rlib
libgsgdt-3b2948ff08479b47.rlib
libhashbrown-2d97545508d04cb0.rlib
libhashbrown-98ad7ec034c50272.rlib
libif_chain-374f4777cdced51d.rlib
libindexmap-cd9736ad18b22a6d.rlib
libinstant-740b6396c2cf92e6.rlib
libitertools-69ccf60104f03065.rlib
libitoa-0e85d057e86ce036.rlib
libjobserver-605ed4eac054b39e.rlib
liblazy_static-691fa15422f5529a.rlib
liblibc-70d15b3d84a45296.rlib
liblibc-f96ee85a4c61666d.rlib
liblock_api-283aa0b0190db7d0.rlib
liblog-b7f97a4e1c99d537.rlib
libmatchers-e56f0d8a5bcbf77f.rlib
libmaybe_uninit-03579d9a93bbee5c.rlib
libmd5-4f05da6bbf208e7e.rlib
libmeasureme-018308267591c624.rlib
libmemchr-43932a8375679d78.rlib
libmemchr-756a02a93f891b6e.rlib
libmemmap2-d326e707a7776975.rlib
libmemoffset-385d2dc165a46ed6.rlib
libminiz_oxide-10495ac7f6cf730b.rlib
libnum_cpus-a4733f52977ecb06.rlib
libnum_integer-fb3a63b61db373a9.rlib
libnum_traits-dcd013873ffe6cf1.rlib
libobject-4d6aa1d75806de3a.rlib
libobject-df75107b2336553a.rlib
libodht-86df1ffcc424b143.rlib
libopaque_debug-feba9054053cec72.rlib
libpanic_abort-7998ed82e0ce1238.rlib
libpanic_unwind-4dd37293767792e7.rlib
libparking_lot-c66fbc5e678ccf46.rlib
libparking_lot_core-dd6aa233ef1970ae.rlib
libpathdiff-6949c318fcde6a08.rlib
libpetgraph-31adaf77cec585cf.rlib
libpin_project_lite-568344579ca899e3.rlib
libpolonius_engine-38d97690ef7fa96d.rlib
libppv_lite86-51d163a6c63219ef.rlib
libproc_macro-befc48b76fd80151.rlib
libproc_macro2-d8161701b12811cf.rlib
libprofiler_builtins-574c347c73ef167e.rlib
libpsm-d37d97467c12e405.rlib
libpunycode-c9c86ad81a5bd293.rlib
libquote-7a9f915f0e3cebdb.rlib
librand-38e09feaa6618b00.rlib
librand-8abe263b354fde3b.rlib
librand_chacha-1bce676c6c3932dd.rlib
librand_chacha-dfe16e5e7dabb6ea.rlib
librand_core-2351b58230850b0b.rlib
librand_core-93e7bb1493fa21fa.rlib
librand_xoshiro-c34a2e7645369e84.rlib
libregex-7b830d00d6b64496.rlib
libregex_automata-d862beb465fbf070.rlib
libregex_syntax-23a489a304b7fe62.rlib
libremove_dir_all-d6eb88ce4f3d5794.rlib
librls_data-c3bd853f16cbf295.rlib
librls_span-e9b27280d957b800.rlib
librustc-nightly_rt.asan.dylib
librustc-nightly_rt.lsan.dylib
librustc-nightly_rt.tsan.dylib
librustc_apfloat-bf5860fa27d5080e.rlib
librustc_arena-19abc7d60d05ade1.rlib
librustc_ast-5cad5c30997b7f71.rlib
librustc_ast_lowering-7c5d42dd791abcf9.rlib
librustc_ast_passes-fca81ccd89148de5.rlib
librustc_ast_pretty-289e74dbb803d37e.rlib
librustc_attr-a693f69f4ea7fc32.rlib
librustc_borrowck-3f9130fa1b4794a7.rlib
librustc_builtin_macros-a98da287750aedd9.rlib
librustc_codegen_llvm-4e9043d23ca49f00.rlib
librustc_codegen_ssa-f9a272bbdd24023f.rlib
librustc_const_eval-1acfa38a8eadbcdd.rlib
librustc_data_structures-696aefd007062d3d.rlib
librustc_demangle-0377913de8effbb8.rlib
librustc_demangle-399b1e9c4f30a8e9.rlib
librustc_driver-8b8d7e07aaf47833.dylib
librustc_error_codes-251149578a477c1f.rlib
librustc_errors-cc90a7bf4ca2d24f.rlib
librustc_expand-1da88ed8d0333ec0.rlib
librustc_feature-9b8e9b3b26421b1a.rlib
librustc_fs_util-b8e669560b08d9aa.rlib
librustc_graphviz-e479e6c7809277d5.rlib
librustc_hash-43cd44e235ce6c09.rlib
librustc_hir-066182575dea3707.rlib
librustc_hir_pretty-0d80777e609e4a70.rlib
librustc_incremental-caaca0ac28b30059.rlib
librustc_index-8af6a0f025068921.rlib
librustc_infer-99f93df126209fa2.rlib
librustc_interface-3a8b61b7fd55a62e.rlib
librustc_lexer-c520f482e86b2028.rlib
librustc_lint-265b3ac770384f78.rlib
librustc_lint_defs-8ac231b741ada266.rlib
librustc_llvm-8c5e06fd356aae56.rlib
librustc_macros-bda58a55fdeb795d.dylib
librustc_metadata-9bbc68502801e63c.rlib
librustc_middle-5b726fae3eac833e.rlib
librustc_mir_build-71fe2cc2548f0fe0.rlib
librustc_mir_dataflow-c4e8b7d3d3980cb4.rlib
librustc_mir_transform-2df512ad8f484858.rlib
librustc_monomorphize-e572b03902d7d6f5.rlib
librustc_parse-8df8624a8c1cd0f5.rlib
librustc_parse_format-519717a96bcf70f9.rlib
librustc_passes-2507ae9f1e229789.rlib
librustc_plugin_impl-76993a9d43f27d29.rlib
librustc_privacy-eca3e6a38d215840.rlib
librustc_query_impl-fdf196f1a97f2015.rlib
librustc_query_system-ff2ba09866763dc0.rlib
librustc_rayon-54e573fa397a7ae9.rlib
librustc_rayon_core-f5f292ff931c017f.rlib
librustc_resolve-4bda6b1e3e665b43.rlib
librustc_save_analysis-074586cc44a73ca3.rlib
librustc_serialize-dc69680bfe8f5042.rlib
librustc_session-7a5a40a8e1651635.rlib
librustc_span-9036cd274e6c491b.rlib
librustc_std_workspace_alloc-2563220abaf5c9d7.rlib
librustc_std_workspace_core-95a7e52c78a3fba1.rlib
librustc_std_workspace_std-388cac5205d1a738.rlib
librustc_symbol_mangling-232969ae7ceff3e4.rlib
librustc_target-99800c5113d918ad.rlib
librustc_trait_selection-d407cc9d53ce3bdc.rlib
librustc_traits-8e62ef8840df6748.rlib
librustc_ty_utils-8e4141cc92f8df42.rlib
librustc_type_ir-7f0ab92a0438ba5d.rlib
librustc_typeck-5bbae005bcfd5419.rlib
libryu-b3a942810826b1d5.rlib
libscoped_tls-89bfd12d536807b8.rlib
libscopeguard-ea5416a98244f19e.rlib
libserde-7e47d9f9ad4c9b49.rlib
libserde_derive-44bcab26e0c53094.dylib
libserde_json-39b772e525416084.rlib
libsha1-38ebab71d0fea2ad.rlib
libsha2-1b5e365409f9cdb9.rlib
libsharded_slab-a8793b460233e3a6.rlib
libsmallvec-a0c19dae634ae0fe.rlib
libsnap-efe6a54de152cf0f.rlib
libstable_deref_trait-668126ee22b3bc2e.rlib
libstacker-82335e64ccd67ca3.rlib
libstd-3287db6a8d065908.dylib
libstd-3287db6a8d065908.rlib
libstd_detect-074fc3d682279d8b.rlib
libsyn-c8bc1691e8ed5724.rlib
libsynstructure-b828b5806b1caf59.rlib
libtempfile-44fc61ad5c926de2.rlib
libtermcolor-c02a1779fa5cf817.rlib
libtermize-afd70c028576eba2.rlib
libtest-e07eca8328691328.dylib
libtest-e07eca8328691328.rlib
libthread_local-fdfba8ff97ff3647.rlib
libtikv_jemalloc_sys-0a2391642a0c888c.rlib
libtikv_jemallocator-ab3d6b0287dee438.rlib
libtinyvec-0354f89d7f222bd7.rlib
libtracing-429f0e4e2d535f2d.rlib
libtracing_attributes-0930e2d22afd68a3.dylib
libtracing_core-356678add3eb4f67.rlib
libtracing_log-0e5d05d98533f58d.rlib
libtracing_serde-2b5e1b9bcad3c677.rlib
libtracing_subscriber-230c1b7f71a1d097.rlib
libtracing_tree-ce591d5ab7e3f363.rlib
libtypenum-6855b005c9d0b0ed.rlib
libunicode_normalization-d19ba9e76b1e4148.rlib
libunicode_script-87f34f851f4b8da2.rlib
libunicode_security-8cd4e5e2ec35ba38.rlib
libunicode_width-2933b5a23f0f83ea.rlib
libunicode_width-bb75058dd7f6eaf1.rlib
libunicode_xid-0176a3e80fc853e6.rlib
libunicode_xid-4a72edfb0e0c4c45.rlib
libunwind-49254d89d854ae53.rlib

**Comment by willcrichton** [comment]
Hmm, it's possible that the macOS / arm build isn't quite working correctly. One last thing. Try:

```
cargo +nightly-2021-10-08 install --force flowistry
```

Then try running it in VSCode.

**Comment by ArbilGit** [comment]
The error disappeared! However, the extension doesn't seem to work - it returns "The function has no effects!" or "slice on "name" did not generate any results" on everything.

Also, after issuing a Flowistry command, there is a "Waiting for Flowistry" popup for 10-15 seconds before these empty results are returned, don't know if the delay is expected.

**Comment by willcrichton** [comment]
Well that doesn't seem right other. If you have the time, can you try:

```
git clone https://github.com/willcrichton/flowistry
cd flowistry
cargo test
```

I know that Flowistry breaks on Windows for inexplicable reasons, but macOS / ARM would be more surprising to me. Good to make sure all the unit tests pass.

The "Waiting for Flowistry" should, theoretically, only happen the first time you run it (to type-check your dependencies) and then be fast afterwards. But I have some performance optimizations that will be shipping in the next version.

**Comment by ArbilGit** [comment]
Sure thing. All tests pass.

To be clear, when I ran `cargo +nightly-2021-10-08 install --force flowistry`, I did not uninstall/reinstall the VSCode extension

**Comment by scullionw** [comment]
I have the same issue, did you manage to fix it @ArbilGit? On M1 as well..

for reference, the vscode installation works fine, but when trying to run (ex: a backwards highlight), I get:

```
Flowistry could not run because your project failed to build with error:
error: failed to run `rustc` to learn about target-specific information

Caused by:
  process didn't exit successfully: `/Users/scullionw/.cargo/bin/flowistry-driver rustc - --crate-name ___ --print=file-names --crate-type bin --crate-type rlib --crate-type dylib --crate-type cdylib --crate-type staticlib --crate-type proc-macro --print=sysroot --print=cfg` (signal: 6, SIGABRT: process abort signal)
  --- stderr
  dyld[55172]: Library not loaded: @rpath/librustc_driver-df51962b1734ccf7.dylib
    Referenced from: /Users/scullionw/.cargo/bin/flowistry-driver
    Reason: tried: '/Users/scullionw/.rustup/toolchains/nightly-2022-01-17-aarch64-apple-darwin/lib/librustc_driver-df51962b1734ccf7.dylib' (no such file), '/Users/scullionw/.rustup/toolchains/nightly-2022-01-17-aarch64-apple-darwin/lib/librustc_driver-df51962b1734ccf7.dylib' (no such file), '/Users/scullionw/lib/librustc_driver-df51962b1734ccf7.dylib' (no such file), '/usr/local/lib/librustc_driver-df51962b1734ccf7.dylib' (no such file), '/usr/lib/librustc_driver-df51962b1734ccf7.dylib' (no such file)
```

**Comment by ArbilGit** [comment]
@scullionw no, I haven't. I haven't tried the newest version though

**Comment by willcrichton** [comment]
@ArbilGit @scullionw when you get the chance, can you try reinstalling Flowistry through the marketplace? Or activate the extension if you have it disabled. I just published v0.5.1.

**Comment by ArbilGit** [comment]
@willcrichton Thanks for the ping! The new version installed smoothly. When the extension activates, in the Flowistry Output panel:

```
Running command: 	cargo +nightly-2022-02-17 flowistry preload
error: Found argument 'preload' which wasn't expected, or isn't valid in this context
```

and similarly, when trying to enter focus mode, the VSCode pane:

```
Flowistry could not run because your project failed to build with error:
error: Found argument 'spans' which wasn't expected, or isn't valid in this context
```

and the output:

```
Running command: 	cargo +nightly-2022-02-17 flowistry spans /Users/me/Documents/Projects/Rust/my_project/src/main.rs
error: Found argument 'spans' which wasn't expected, or isn't valid in this context
```

I `cargo clean`ed and `cargo build` to verify the project builds. Mind you, it's not impossible something in my toolchain is fucked independently from Flowistry.

**Comment by scullionw** [comment]
I am experiencing the same issues: `Found argument 'spans' which wasn't expected, or isn't valid in this context`

**Comment by willcrichton** [comment]
Hmm, seems like the IDE extension didn't successfully overwrite your existing binaries. Can you try this:

```
rm ~/.cargo/bin/cargo-flowistry ~/.cargo/bin/flowistry-driver
```

And then reload VSCode and try again?

**Comment by willcrichton** [comment]
Actually, I ended up fixing the not-overwriting issue in v0.5.2. If you reload VSCode, it should update Flowistry again and fix this issue.

**Comment by scullionw** [comment]
Now I am getting the same error as initially `Library not loaded: @rpath/librustc_driver-f23160ece52a828b`, and a moment after I also get:

```
Flowistry could not run because your project failed to build with error:
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', crates/flowistry_ide/src/bin/cargo-flowistry.rs:65:44
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by willcrichton** [comment]
Ah ok I think I see the issue. The M1 build is happening on a Github Actions runner that's x86_64. So the actual compiler itself is built for x86_64. Flowistry is getting cross-compiled to ARM, but Rustc is still inserting the dylib paths as if the binary is being run on x86_64 and not ARM.

I will investigate a solution, thank you both for your patience and support.

**Comment by ArbilGit** [comment]
Can confirm exactly the same new issue.

Thanks for working on this. It never ceases to amaze me how generous people in this field are with uncompensated time and expertise.

**Comment by willcrichton** [comment]
Alright, I pushed a new version 0.5.3 where ARM pre-builds are disabled. Now Flowistry should install from source when you activate the extension. Let me know if that works.

**Comment by scullionw** [comment]
that did the trick, thanks @willcrichton!

**Comment by willcrichton** [comment]
Ok great. I will close this for now, and try to get pre-builds working in the future.
