### ISSUE TITLE
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value'

### ISSUE THREAD

**Issue by rukai** [willcrichton/flowistry#38]
I tried using flowistry on the project I was working on (https://github.com/rust-windowing/winit) so I installed it and then pressed the flowistry button in the bottom toolbar and got this error:
![image](https://user-images.githubusercontent.com/5120858/155827238-96e6ce38-6760-45e5-8d9b-91b1121661c1.png)

**Comment by rukai** [comment]
Did you mean v0.5.7?
It updated to v0.5.7 and now I am getting:
![image](https://user-images.githubusercontent.com/5120858/155863817-2db1451f-5a03-48de-a866-59706e36dc13.png)

**Comment by willcrichton** [comment]
Ah yes I mean 0.5.7. And hmm, that error should only happen if `cargo-flowistry` failed to install. 

Can you dump the logs from Flowistry? You can access them by clicking this button:

![Screen Shot 2022-02-26 at 6 04 21 PM](https://user-images.githubusercontent.com/663326/155865332-da3f9623-67cd-49af-a16e-5cbc73924529.png)

And then going to this tab:

![Screen Shot 2022-02-26 at 6 04 36 PM](https://user-images.githubusercontent.com/663326/155865335-8a7774d2-8b76-429a-95ca-12f0541bd324.png)

**Comment by rukai** [comment]
![image](https://user-images.githubusercontent.com/5120858/155866045-c11301fb-b463-4dd2-989b-4d93b40b9534.png)

**Comment by willcrichton** [comment]
Ah, I'm guessing you don't have `$HOME/.cargo/bin` on your `PATH` right?

**Comment by rukai** [comment]
I do actually.
But it looks like the problem is that cargo-flowistry lacks executable permissions.
![image](https://user-images.githubusercontent.com/5120858/155866386-cd29528c-5c6a-4932-8b83-c6e79236fbd2.png)

**Comment by rukai** [comment]
Manually setting the executable bit for those files gets it this far:
![image](https://user-images.githubusercontent.com/5120858/155866523-8fa80c7d-72ea-4bde-b344-c94aca999288.png)

**Comment by willcrichton** [comment]
Ok, I just added a commit which should fix all the problems you've observed thus far. v0.5.8 will be available shortly. Thank you for your help and your patience!

PS one issue you will probably run into is Flowistry doesn't yet support running on code that isn't on your native `target_arch`, so you can't use it on a lot of `platform_impl`.

**Comment by rukai** [comment]
My flowistry updated to v0.5.8 but it didnt solve the problem.
Looking into it a bit, it seems to be caused by my rust-toolchain.toml file which simply contains:
```
[toolchain]
channel = "stable"
components = [ ]
```

**Comment by rukai** [comment]
My flowistry updated to v0.5.8
But I still cant get past the "Could not find target for path issue"
That said I did manage to track down what is causing it on my system.
The path to the project involves a symlink.
In the path in the screenshotted error the `Projects` directory is a symlink.

**Comment by willcrichton** [comment]
Ok see if 0.5.9 solves your symlink issue.

**Comment by rukai** [comment]
The symlink issue is solved, winit is working fine!

However I'm still hitting the "Could not find target for path" issue on files in this crate https://github.com/shotover/shotover-proxy/blob/main/shotover-proxy/src/main.rs

**Comment by willcrichton** [comment]
I just published 0.5.10 which should solve that issue as well.

**Comment by rukai** [comment]
Can confirm that one is fixed!

Heres a new one: 
![image](https://user-images.githubusercontent.com/5120858/156267611-435a1e67-ed51-43d7-b22e-49a9fc7be35d.png)
Encountered on this file https://github.com/shotover/shotover-proxy/blob/main/shotover-proxy/src/transforms/filter.rs

**Comment by willcrichton** [comment]
Ok this is fixed in 0.5.11 (out in a few minutes).

I will note that in general, Flowistry doesn't have a good solution yet for handling async functions. This is because at the MIR level, async functions have already been chopped up into multiple closures, and Flowistry only analyzes one function body at a time. So in the case of `QueryTypeFilter::transform`, if you select one of the arguments, it will appear to be irrelevant to the body of the function. Also MIR source-mapping is in general pretty bad, especially for async...

**Comment by rukai** [comment]
I dont have any more panics, so I'll go ahead and close this issue.
Thanks for your quick responses!
