### ISSUE TITLE
Cannot find rustup when launching VS Code from the dock/finder

### ISSUE THREAD

**Issue by brendanzab** [willcrichton/flowistry#4]
When I launch VS Code from the dock (on macOS), and then try to install the extension, I get an error saying that the extension could not find Rustup. I assume it was not on VS Code's PATH at this point. Alas I didn't think to copy the error message at the time, so I can't remember what it was exactly, but it was along the lines of: "could not find rustup (/bin/sh)"

The fix was to use the `code` command to launch VS Code from the terminal, then the installation of flowistry proceeded as expected when prompted. Not sure what the normal solution to this - I assume there are some janky ways around it people employ, but I thought I'd let you know rather than suffering in silence!

**Comment by willcrichton** [comment]
Thanks for the issue @brendanzab! I just pushed a version v0.3.7 that should fix this issue (I think).

In ~30 minutes, can you try and reopen VSCode in the normal way (not via `code`) and re-install Flowistry when it prompts you?

**Comment by brendanzab** [comment]
Would I need to uninstall the crate as well somehow?

**Comment by willcrichton** [comment]
The crate version is pinned to the package version, so when the IDE extension updates to `0.3.7` it should detect that the crate is out-of-date and ask you to update.

**Comment by brendanzab** [comment]
Posting this follow up report here, to avoid making more issues:

# Problem

Attempted to install v0.3.7 from an instance of VS Code launched from dock. 

# Logs


Error message:
```
/bin/bash: rustup: command not found
```

Full log: https://paste.rs/7Vs

**Comment by willcrichton** [comment]
@brendanzab can you try updating to 0.3.9 and see if that fixes it? It should run scripts in whatever your `$SHELL` is.

**Comment by willcrichton** [comment]
I think this is fixed so closing for now, but please reopen if you encounter the same issue.
