### ISSUE TITLE
Crate install failed

### ISSUE THREAD

**Issue by wezm** [willcrichton/flowistry#5]
# Problem

I tried installing the plugin. It installed then said that the crate needed to be installed, I clicked the button to do that. It sat there for a while then showed the error below.

<img width="442" alt="Screenshot from 2021-09-23 10-20-12" src="https://user-images.githubusercontent.com/21787/134438808-a2d032bf-2c89-4bef-ba89-98fd27e6a370.png">

# Host

**OS:** Arch Linux x86
**Rust:** rustc 1.54.0 (a178d0322 2021-07-26) managed with `rustup`
**VS Code:** 

Version: 1.60.1
Commit: 83bd43bc519d15e50c4272c6cf5c1479df196a4d
Date: 2021-09-10T17:06:57.931Z
Electron: 13.1.8
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Linux x64 5.14.6-arch1-1

Error message:
```
error: could not find `flowistry` in registry `crates-io` with version `=0.3.6`
```

Full log: https://paste.rs/vUr

**Comment by willcrichton** [comment]
Hi @wezm! Thanks for filing a bug. I think you hit a race condition, since it seems the VSCode marketplace propagates faster than crates.io. I also just pushed v0.3.7, which means if you try again right now you could conceivably hit this error again... 

Can you try reinstalling in ~15 minutes?

**Comment by wezm** [comment]
Tried again and it installed successfully. Thanks 👍
