### ISSUE TITLE
Flowistry (in vscode) doesn't seem to like trait default implementations

### ISSUE THREAD

**Issue by gwillen** [willcrichton/flowistry#52]
I've been poking around an existing project in flowistry, and finding places where it seems to fail to do anything.

One such place: It seems to be blind to the bodies of default method implementations in traits.

When I click in one, the output window doesn't show anything (it doesn't trigger a run of "flowistry focus", and the highlighting in the window doesn't change (it stays on whatever function I was previously looking at.) This seems to be the same behavior as when I click on a line that doesn't contain a function at all.

**Comment by willcrichton** [comment]
Thanks for the report. This will be fixed in the next release.
