### ISSUE TITLE
Panic on Vec::sort_by_key()

### ISSUE THREAD

**Issue by burjui** [willcrichton/flowistry#54]
In the following program
```rust
fn main() {
    let mut v: Vec<&str> = vec![];
    v.sort_by_key(|x| x.len());
}
```
clicking on the `sort_by_key` method causes a panic with `flowistry` v0.5.25
```
Flowistry could not run because your project failed to build with error:
thread 'rustc' panicked at 'internal error: entered unreachable code: ReLateBound(DebruijnIndex(0), BoundRegion { var: 0, kind: BrAnon(0) })', crates/flowistry/src/mir/aliases.rs:645:12
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error: could not compile `rust-playground`
```
<details>
<summary>With backtrace enabled:</summary>
<pre>
Flowistry could not run because your project failed to build with error:
thread 'rustc' panicked at 'internal error: entered unreachable code: ReLateBound(DebruijnIndex(0), BoundRegion { var: 0, kind: BrAnon(0) })', crates/flowistry/src/mir/aliases.rs:645:12
stack backtrace:
   0: rust_begin_unwind
             at /rustc/b2eed72a6fbf254e7d44942eaa121fcbed05d3fb/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/b2eed72a6fbf254e7d44942eaa121fcbed05d3fb/library/core/src/panicking.rs:142:14
   2: <flowistry::mir::aliases::LoanCollector as rustc_middle::ty::fold::TypeVisitor>::visit_region
   3: rustc_middle::ty::structural_impls::<impl rustc_middle::ty::fold::TypeFoldable for rustc_middle::ty::Ty>::super_visit_with
   4: <flowistry::mir::aliases::LoanCollector as rustc_middle::ty::fold::TypeVisitor>::visit_ty
   5: rustc_middle::ty::structural_impls::<impl rustc_middle::ty::fold::TypeFoldable for rustc_middle::ty::Ty>::super_visit_with
   6: <flowistry::mir::aliases::LoanCollector as rustc_middle::ty::fold::TypeVisitor>::visit_ty
   7: rustc_middle::ty::structural_impls::<impl rustc_middle::ty::fold::TypeFoldable for rustc_middle::ty::Ty>::super_visit_with
   8: <flowistry::mir::aliases::LoanCollector as rustc_middle::ty::fold::TypeVisitor>::visit_ty
   9: rustc_middle::ty::structural_impls::<impl rustc_middle::ty::fold::TypeFoldable for rustc_middle::ty::Ty>::super_visit_with
  10: <flowistry::mir::aliases::LoanCollector as rustc_middle::ty::fold::TypeVisitor>::visit_ty
  11: flowistry::mir::aliases::Aliases::collect_loans
  12: flowistry::cached::Cache<In,Out>::get
  13: flowistry::infoflow::analysis::FlowAnalysis::transfer_function::{{closure}}
  14: flowistry::infoflow::analysis::FlowAnalysis::transfer_function
  15: rustc_middle::mir::visit::Visitor::visit_statement
  16: flowistry::mir::engine::iterate_to_fixpoint
  17: std::thread::local::LocalKey<T>::with
  18: flowistry::infoflow::compute_flow
  19: <F as flowistry_ide::plugin::FlowistryAnalysis>::analyze
  20: rustc_interface::passes::QueryContext::enter
  21: <flowistry_ide::plugin::FlowistryCallbacks<A,T> as rustc_driver::Callbacks>::after_parsing
  22: <rustc_interface::interface::Compiler>::enter::<rustc_driver::run_compiler::{closure#1}::{closure#2}, core::result::Result<core::option::Option<rustc_interface::queries::Linker>, rustc_errors::ErrorGuaranteed>>
  23: rustc_span::with_source_map::<core::result::Result<(), rustc_errors::ErrorGuaranteed>, rustc_interface::interface::create_compiler_and_run<core::result::Result<(), rustc_errors::ErrorGuaranteed>, rustc_driver::run_compiler::{closure#1}>::{closure#1}>
  24: rustc_interface::interface::create_compiler_and_run::<core::result::Result<(), rustc_errors::ErrorGuaranteed>, rustc_driver::run_compiler::{closure#1}>
  25: <scoped_tls::ScopedKey<rustc_span::SessionGlobals>>::set::<rustc_interface::interface::run_compiler<core::result::Result<(), rustc_errors::ErrorGuaranteed>, rustc_driver::run_compiler::{closure#1}>::{closure#0}, core::result::Result<(), rustc_errors::ErrorGuaranteed>>
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
error: could not compile `rust-playground`
</pre>
</details>

**Comment by willcrichton** [comment]
Thanks for the report @burjui. I'll ship a release with the patch today.
