### ISSUE TITLE
Allow setting rustflags required to build codebase

### ISSUE THREAD

**Issue by duarten** [willcrichton/flowistry#56]
If a codebase requires a rustflag to be able to build (e.g., `tokio_unstable`), then flowistry won't be able to do it. It would be nice if flowistry picked up .cargo/config or accepted a set of rustflags.

**Comment by willcrichton** [comment]
Good suggestion. Seems like Rust Analyzer has a config option for this, we could do something similar: https://users.rust-lang.org/t/how-to-tell-rust-analyzer-about-target-features/75332/3

**Comment by repi** [comment]
we just ran into this exact same problem and same missing flag for unstable tokio features when testing out flowistry in our codebase, so +1.

**Comment by willcrichton** [comment]
I realized actually this was actually a bug due to Flowistry unnecessarily overriding RUSTFLAGS. It will be fixed in the next release.

**Comment by repi** [comment]
thanks can confirm this fixed in the latest release resolved the issue we were seeing!
