### ISSUE TITLE
Improve error messages

### ISSUE THREAD

**Issue by janosimas** [willcrichton/flowistry#7]
I work in a project with some specific `rust-toolchain`, currently: `nightly-2020-08-13`.
When I tried to use flowistry, but it failed with an unhelpful error message of some build error.

It would be nice to have some more informative error message, specially in the case of a system configuration issue.
Following I added some more details of my issue.

After investigating the command line tool, I found that it was not finding `librustc-driver-...`.
I "fixed" this issue adding the lib path to ldconfig and fter that I got this message from the command line tool:
```
error[E0514]: found crate `std` compiled by an incompatible version of rustc
  |
  = help: please recompile that crate using this compiler (rustc 1.57.0-nightly (aa8f2d432 2021-09-18))
  = note: the following crate versions were found:
          crate `std` compiled by rustc 1.47.0-nightly (576d27c5a 2020-08-12): /home/user/.rustup/toolchains/nightly-2020-08-13-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-afd4b9aba051f3ad.rlib

error: aborting due to previous error
```

During all this process the error message in VSCode was always the same of some build error.

**Comment by willcrichton** [comment]
Thanks for the bug report @janosimas! Can you tell me what the error message was?

**Comment by willcrichton** [comment]
Also if you can reproduce the bug, the "Report bug" button will post an issue containing logs with a lot more information about what happened.

**Comment by willcrichton** [comment]
Lastly: I just pushed 0.3.10 which should fix your issue with not finding the appropriate libraries.

**Comment by janosimas** [comment]
I checked the bug report and I can see the issue.
The two commands executed do not respect the `rust-toolchain` file, the toolchain should be `nightly-2020-08-13`:
```sh
$ cargo +nightly-2021-09-19 flowistry -V
$ cargo +nightly-2021-09-19 flowistry backward_slice /home/user/dev/client/src/env.rs 1308 1308
```
If I try to build with `nightly-2021-09-19`, I get the same build errors.

When I try to execute:
```sh
$ cargo +nightly-2020-08-13 flowistry backward_slice /home/user/dev/client/src/env.rs 1308 1308
```
I don't get the rust library error but I get a new error:
```
/home/user/.cargo/bin/cargo-flowistry: error while loading shared libraries: libLLVM-13-rust-1.57.0-nightly.so: cannot open shared object file: No such file or directory
```

**Comment by janosimas** [comment]
The error in VSCode is `Flowistry error: build failed`

**Comment by willcrichton** [comment]
@janosimas it's actually intended that Flowistry will execute with a different toolchain than was used to compile your project. 

Can you try one more time and make sure Flowistry is up-to-date? 0.3.10 just released and should fix your issue.

Also I will try to make the error message more useful.

**Comment by janosimas** [comment]
I'll try it tomorrow and post the result.

In any case, using a different toolchain will fail to build this project.

**Comment by janosimas** [comment]
The message is still a build error, I can see in the log that the correct tooling and dependencies were installed.
The build error is caused by not using the correct toolchain.

I'll not post the full log because of company policies.

**Comment by willcrichton** [comment]
Unfortunately, Flowistry has to be built with a specific toolchain, so I can't change it to build with your project's toolchain. Is the build error about something that existed in your project's nightly (1.47) but not the current nightly (1.57)?

**Comment by janosimas** [comment]
I understand the limitation, that's why I just wanted to improve the error message.
"Build error" is a vague and even in fair cases like this, may cause a user to scratch his head without a clue.

The errors are mostly related to old rust syntax that was deprecated.
