### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by andrey-kuprianov** [willcrichton/flowistry#8]
# Problem

The build failed while compiling the extension

# Logs

**OS:** darwin (20.6.0)
**VSCode:** 1.61.0-insider
**Error message**
```
  build failed
```

**Full log:** https://paste.rs/XHb

**Comment by willcrichton** [comment]
Hi @andrey-kuprianov thanks for the report. It seems like this is a Rust nightly bug on M1 macs: https://github.com/rust-lang/rust/issues/89085

I will update the nightly and this should fix your issue.
