### ISSUE TITLE
install script failed with fish shell

### ISSUE THREAD

**Issue by deontologician** [willcrichton/flowistry#9]
https://github.com/willcrichton/flowistry/blob/1b8fedc5e288fa1a7c8c5d252369a96439e681a8/ide/src/setup.ts#L20

I just got an error that seems to stem from the install script failing in fish shell. I think `|| true` should just ignore the value of `process.env.SHELL`

I'm not familiar with `child_process` here, but the script has a bash hashbang etc, so I'm guessing it's something about how the script is being invoked that's an issue

**Comment by willcrichton** [comment]
@deontologician can you post the full logs? If you use the "Report bug" button, it will autogenerate them for you.

**Comment by deontologician** [comment]
Sorry, I lost it. I'll try to reproduce it

**Comment by deontologician** [comment]
# Logs


**OS:** linux (5.12.10-300.fc34.x86_64)
**VSCode:** 1.60.1
**Error message**
```
 ^
```

**Full log:** https://paste.rs/2Ki

**Comment by willcrichton** [comment]
I think this is fixed so closing for now, but please reopen if the issue persists.
